version: "2.4"

services:

  nginx:
    container_name: myproject_nginx
    build:
      context: ./nginx
      dockerfile: dev/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/dev/dev.conf:/etc/nginx/nginx.conf:ro
    networks:
      - main

  postgres:
    container_name: myproject_postgres
    image: postgres:14
    networks:
      - main
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  redis:
    container_name: myproject_redis
    image: redis:alpine
    volumes:
      - redis-data:/data
    networks:
      - main

  backend: &backend
    container_name: myproject_backend
    build:
      context: ./backend
      target: local_development
    command:
      - "python3"
      - "manage.py"
      - "runserver"
      - "0.0.0.0:8000"
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    networks:
      - main
    environment:
      - CELERY_TASK_ALWAYS_EAGER=${CELERY_TASK_ALWAYS_EAGER:-0}
      - DJANGO_EMAIL_HOST=mailhog
      - DEBUG=1
      - POSTGRES_SERVICE_HOST=postgres
      - REDIS_SERVICE_HOST=redis
      - DJANGO_SETTINGS_MODULE=backend.settings.development
      # PIDFILE is for Celery Beat
      - PIDFILE=/code/celerybeat.pid
    depends_on:
      - postgres
      - redis

  celery_worker:
    <<: *backend
    container_name: myproject_celery_worker
    command:
      - "python3"
      - "manage.py"
      - "start_celery_worker"
    ports: []

  celery_beat:
    <<: *backend
    container_name: myproject_celery_beat
    command:
      - python3
      - manage.py
      - start_celery_beat
    ports: []

  # migrate command
  migrate:
    <<: *backend
    container_name: myproject_migrate
    command:
      - python3
      - manage.py
      - migrate
    ports: []
    depends_on:
      - postgres
      - redis
      - backend
    restart: "on-failure"

  notebook:
    <<: *backend
    container_name: myproject_notebook
    command:
      - python3
      - manage.py
      - shell_plus
      - --notebook
    ports:
      - "8888:8888"

  mailhog:myproject_
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - main

  flower:
    container_name: myproject_flower
    image: mher/flower
    ports:
      - "49555:5555"
    networks:
      - main
    depends_on:
      - celery_worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1

  redis_commander:
    container_name: myproject_redis_commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOST=redis
    ports:
      - "8085:8081"
    depends_on:
      - "redis"
    networks:
      - main

volumes:
  pg-data:
  redis-data:

networks:
  main:
    driver: bridge
